# generated by datamodel-codegen:
#   filename:  sample.yaml
#   timestamp: 2025-09-12T08:59:55+00:00

from __future__ import annotations
from pydantic import BaseModel, EmailStr, Field
from datetime import datetime


class User(BaseModel):
    id: int | None = Field(None, example=1)
    username: str | None = Field(None, example='johndoe')
    email: EmailStr | None = Field(None, example='johndoe@example.com')
    is_active: bool | None = Field(None, example=True)
    created_at: datetime | None = Field(None, example='2024-01-01T12:00:00Z')
    updated_at: datetime | None = Field(None, example='2024-01-02T12:00:00Z')


class UserCreate(BaseModel):
    username: str = Field(..., example='johndoe')
    email: EmailStr = Field(..., example='johndoe@example.com')
    hashed_password: str = Field(..., example='hashed_password_here')


class UserUpdate(BaseModel):
    username: str | None = Field(None, example='johndoe_new')
    hashed_password: str | None = Field(None, example='new_hashed_password_here')
    is_active: bool | None = Field(None, example=False)
